fixed bugs that CNN was training during eval. Fixed bug that CNN was …
DiMaths/beat-detection pull request #7
Opened 2024-06-15 09:26 UTC by in1ght

…not working due to new variables, small adjustments.

2024-06-15 12:45 UTC, in1ght commented on melspect_CNN.py
that sets up in cmd, but the CNN needs both training and evaluating (i.e. not training). This small remark makes system be in a training mode forever and hence will lead to poor results and error if we use test for evaluating.

2024-06-15 12:54 UTC, DiMaths requested changes

2024-06-15 12:54 UTC, DiMaths commented on detector.py
> +        # GT.update(dict_train)
Why use train and train extra constants if we have parsed input dir as options.indir?
If you want to train on both folders it's either to actually create 3rd one on your machine called anyhow you like and then just use python3 ./detector.py ./combined_folder/ ./predictions_for_server.json ...

2024-06-15 12:54 UTC, DiMaths commented on melspect_CNN.py
>      print("Working on device",torch.cuda.get_device_name(0))
If CUDA is not installed it crashes. I suggest switch default to no CUDA and using cpu and if CUDA is available then use it or even add --cuda option for potential usage with cpu when CUDA is available...

2024-06-15 12:54 UTC, DiMaths commented on melspect_CNN.py
> +    optimizer = torch.optim.SGD(network.parameters(), lr=0.04, momentum=0.75)
Any reason why using SGD and not something more generic like Adam?

2024-06-15 12:54 UTC, DiMaths commented on melspect_CNN.py
> +                    ground_truth_onsets[i-1] = 0.25
What 0.25 means?

2024-06-15 13:00 UTC, DiMaths commented on melspect_CNN.py
Sorry, now got it, thought it was redundant at first glance. I'll change it back in new commit

2024-06-15 13:07 UTC, DiMaths commented on melspect_CNN.py
Changed it back. But do we treat dataset_val with is_training?

2024-06-15 13:10 UTC, DiMaths commented
Would be nice if you could add the seed to the model and data handling functions. For reproducibility of splits, initialisations etc... I can make it a parser argument with default value later.

2024-06-15 13:11 UTC, in1ght commented on melspect_CNN.py
yes, when we talk about dataset, since there is a ground truth for it, but as a model - no, in print_eval it is automatically stated that it treats model as is_training = False.

There are 2 Classes for it: 
1. Dataset (i.e. is_training = True, then in get_item we also give the ground truth for eval and train purposes)
2. Model (for dropout)

2024-06-15 13:13 UTC, in1ght commented on detector.py
> +        # GT.update(dict_train)
that is for convenience during working with data that has ground truth. You don't wanna model to train on train and then eval on train. This could be indeed done the way you suggested.

2024-06-15 13:15 UTC, in1ght commented on melspect_CNN.py
> +    optimizer = torch.optim.SGD(network.parameters(), lr=0.04, momentum=0.75)
because it was used in one of the paper I read, and because of constast momentum than was a variable. Adam indeed could work better here. I initially worked with AdamW, but did not compare 2.

2024-06-15 13:16 UTC, in1ght commented on melspect_CNN.py
> +                    ground_truth_onsets[i-1] = 0.25
to smooth the model output it was suggested by Jan to give onset value of 0.25 to the neighboring frames next to the real onset.

2024-06-15 13:17 UTC, in1ght commented
Currently working on SLIM RecSys, but will do when I am finished.

2024-06-15 13:27 UTC, DiMaths commented on melspect_CNN.py
Ok, agreed.

2024-06-15 19:25 UTC, DiMaths commented on detector.py
> +        # GT.update(dict_train)
Now dict_train is never used and actually train files seem to be too, so conveniency is to comment out one out of 2 "folders" depending on which you want to train on and on which to evaluate?
But isn't evaluation done on the test split of files from the same folder? I find it more than fine if the model trains and evaluates on files from the same folder, but different ones.

2024-06-15 20:10 UTC, in1ght commented on detector.py
> +        # GT.update(dict_train)
it would require rewriting partially evaluate function, hence I used it different way, but that indeed makes sense. I will fix it on Monday if that works for you.

2024-06-17 21:03 UTC, DiMaths commented on melspect_CNN.py
>      print("Working on device",torch.cuda.get_device_name(0))
Fixed

2024-06-17 21:05 UTC, merged